# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # needs: something esle
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Repo Checkouit
        uses: actions/checkout@v2

      - name: Install prerequisits 
        run: |
          sudo apt install python3-testresources 
          python -m pip install requests
          python -m pip install beautifulsoup4

      # - name: Python Pip Install
      #   # uses: logikal-code/pip-install@51d215f7fc153e741488726defaa8cb84ea35300
      #   uses: logikal-code/pip-install@v1.0.0
      #   with:
      #     # The path to the requirements file
      #     requirements: requirements.txt # optional, default is requirements.txt

      #- name: Run Python Script
      #  run: python beautifulsoap.py
      - name: check syntax
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

      - name: Run Python Script
        run: python beautifulsoap.py

